# Generated by Django 4.2.19 on 2025-02-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelsAndInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='key', max_length=256, unique=True)),
                ('description', models.TextField(db_column='description')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('changed', models.DateTimeField(auto_now=True, db_column='changed')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_column='language_code', max_length=7)),
                ('name', models.CharField(db_column='name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LabelsAndInstructionsLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(db_column='value')),
                ('label_or_instruction', models.ForeignKey(db_column='label_or_instruction', on_delete=django.db.models.deletion.CASCADE, to='imeicheck_bot.labelsandinstructions')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='imeicheck_bot.languages')),
            ],
        ),
        migrations.AddConstraint(
            model_name='labelsandinstructionslanguages',
            constraint=models.UniqueConstraint(fields=('label_or_instruction', 'language'), name='unique appversion'),
        ),
    ]
