# Generated by Django 4.2.19 on 2025-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(db_column='user_id', null=True, unique=True),
        ),
    ]
